---
# Description
- name: Description of playbook "{{ mikey }}"
  hosts: localhost
  gather_facts: true
  vars:
    keyduplicada: "Valor inicial"
    keyduplicada: "Valor sobreescrito"
    key_bien_diccionario: "Valor puesto en el diccionario"
  tasks:
    - name: prueba 
      ansible.builtin.slurp:
        src: ./playbook_prueba.yml
      register: texto
    - name: prueba sfasd 
      ansible.builtin.slurp:
        src: ./playbook_prueba.yml
      register: texto
    - name: Define var
      set_fact:
        varfact: "valor 1"
        
    - name: Define var 2
      set_fact:
        varfact: "valor 1"
        varfact_b: "valor 2"
        cacheable: false  